# Generated by Django 4.0.4 on 2022-05-21 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_category_women_cat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='women',
            name='cat_id',
        ),
        migrations.AddField(
            model_name='women',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='women.category'),
        ),
    ]
